"""
Preprocess Amazon Reviews 2023 raw JSONL.gz files into train/val/test splits.

Steps:
1. Load All_Beauty.jsonl.gz + Electronics.jsonl.gz from data/raw/.
2. Clean review text (strip whitespace, drop empty/very short).
3. Map star ratings to 3 sentiment classes:
   1-2 stars -> NEGATIVE (0), 3 stars -> NEUTRAL (1), 4-5 stars -> POSITIVE (2).
4. Sample up to 100K combined (stratified by label) before splitting.
5. Split 80/10/10 train/val/test with seed=42.
6. Undersample train to 15K per class (45K total balanced).
7. Val + test remain unbalanced (real-world distribution).

Outputs (in data/processed/):
- train.csv, val.csv, test.csv  (columns: review_id, text, label, rating, category)
- split_indices.json             ({"train": [...], "val": [...], "test": [...]})
- dataset_stats.md               (row counts, label distribution, length stats)
"""

import gzip
import json
import random
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# Reproducibility — set before any split/sample operations
random.seed(42)
np.random.seed(42)

REPO_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = REPO_ROOT / "data" / "raw"
PROCESSED_DIR = REPO_ROOT / "data" / "processed"

LABEL_MAP = {1: 0, 2: 0, 3: 1, 4: 2, 5: 2}  # star -> class id
LABEL_NAMES = {0: "NEGATIVE", 1: "NEUTRAL", 2: "POSITIVE"}

TRAIN_PER_CLASS = 15_000   # undersample target per class in train split
# Cap majority class (POSITIVE) before splitting to limit memory while preserving
# minority class rows. Positive reviews are ~85% of raw data; we cap at 3x the
# minority class target to keep the dataset manageable (~100-150K rows total).
MAX_POSITIVE_ROWS = 60_000  # cap class 2 (POSITIVE) before splitting
MIN_TEXT_LEN = 10           # characters — drop very short reviews


def load_jsonl_gz(path: Path, category: str) -> list[dict]:
    """Load records from a gzipped JSONL file, return list of cleaned dicts."""
    records = []
    with gzip.open(path, "rt", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue

            rating_raw = rec.get("rating")
            text_raw = rec.get("text", "")

            if rating_raw is None or not text_raw:
                continue

            try:
                rating = int(round(float(rating_raw)))
            except (ValueError, TypeError):
                continue

            if rating not in LABEL_MAP:
                continue

            text = clean_text(text_raw)
            if len(text) < MIN_TEXT_LEN:
                continue

            records.append(
                {
                    "review_id": rec.get("asin", "") + "_" + rec.get("user_id", "") + "_" + str(rec.get("timestamp", "")),
                    "text": text,
                    "label": LABEL_MAP[rating],
                    "rating": rating,
                    "category": category,
                }
            )
    return records


def clean_text(text: str) -> str:
    """Normalize whitespace; preserve punctuation for BERT tokenizer."""
    text = text.strip()
    # Collapse runs of whitespace/newlines to single space
    text = re.sub(r"\s+", " ", text)
    return text


def undersample_to_target(df: pd.DataFrame, per_class: int, rng: np.random.Generator) -> pd.DataFrame:
    """Undersample each class to per_class rows using provided rng."""
    parts = []
    for label in sorted(df["label"].unique()):
        subset = df[df["label"] == label]
        if len(subset) >= per_class:
            parts.append(subset.sample(n=per_class, random_state=42))
        else:
            # Escalation condition: not enough samples in a class
            print(
                f"WARNING: class {label} ({LABEL_NAMES[label]}) has only {len(subset)} rows "
                f"but target is {per_class}. Using all available.",
                file=sys.stderr,
            )
            parts.append(subset)
    return pd.concat(parts).sample(frac=1, random_state=42).reset_index(drop=True)


def length_stats(series: pd.Series) -> dict:
    """Return mean/median/p95 of character lengths."""
    lengths = series.str.len()
    return {
        "mean": round(float(lengths.mean()), 1),
        "median": round(float(lengths.median()), 1),
        "p95": round(float(lengths.quantile(0.95)), 1),
    }


def write_stats(train: pd.DataFrame, val: pd.DataFrame, test: pd.DataFrame) -> None:
    """Write dataset_stats.md to data/processed/."""
    lines = [
        "# Dataset Statistics\n",
        "Generated by `data/preprocess.py`. Reproducibility seed: 42.\n",
        "",
        "## Split sizes\n",
        f"| Split | Rows |",
        f"|-------|------|",
        f"| train | {len(train):,} |",
        f"| val   | {len(val):,} |",
        f"| test  | {len(test):,} |",
        f"| **total** | {len(train)+len(val)+len(test):,} |",
        "",
        "## Label distribution\n",
        "| Split | NEGATIVE (0) | NEUTRAL (1) | POSITIVE (2) |",
        "|-------|-------------|------------|-------------|",
    ]

    for name, df in [("train", train), ("val", val), ("test", test)]:
        counts = df["label"].value_counts().sort_index()
        neg = counts.get(0, 0)
        neu = counts.get(1, 0)
        pos = counts.get(2, 0)
        lines.append(f"| {name} | {neg:,} | {neu:,} | {pos:,} |")

    lines += [
        "",
        "## Text length stats (characters)\n",
        "| Split | Mean | Median | P95 |",
        "|-------|------|--------|-----|",
    ]
    for name, df in [("train", train), ("val", val), ("test", test)]:
        s = length_stats(df["text"])
        lines.append(f"| {name} | {s['mean']} | {s['median']} | {s['p95']} |")

    lines += [
        "",
        "## Category distribution (train)\n",
        "| Category | Count |",
        "|----------|-------|",
    ]
    for cat, cnt in train["category"].value_counts().items():
        lines.append(f"| {cat} | {cnt:,} |")

    out_path = PROCESSED_DIR / "dataset_stats.md"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}")


def main() -> None:
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

    # 1. Load raw data
    all_records: list[dict] = []
    for fname, category in [("All_Beauty.jsonl.gz", "Beauty"), ("Electronics.jsonl.gz", "Electronics")]:
        path = RAW_DIR / fname
        if not path.exists():
            print(f"ERROR: {path} not found. Run data/download_data.py first.", file=sys.stderr)
            sys.exit(1)
        print(f"Loading {fname}...")
        records = load_jsonl_gz(path, category)
        print(f"  Loaded {len(records):,} valid records from {fname}.")
        all_records.extend(records)

    print(f"Total records loaded: {len(all_records):,}")

    df = pd.DataFrame(all_records)

    # 2. Deduplicate on review_id
    before = len(df)
    df = df.drop_duplicates(subset=["review_id"])
    print(f"After dedup: {len(df):,} rows (removed {before - len(df):,} duplicates)")

    # 3. Cap majority class (POSITIVE=2) to MAX_POSITIVE_ROWS to limit memory.
    #    Minority classes (NEGATIVE, NEUTRAL) are kept in full — they are already
    #    scarce and we need every row to reach 15K/class after the 80% train split.
    pos_mask = df["label"] == 2
    pos_df = df[pos_mask]
    non_pos_df = df[~pos_mask]
    if len(pos_df) > MAX_POSITIVE_ROWS:
        print(f"Capping POSITIVE class from {len(pos_df):,} to {MAX_POSITIVE_ROWS:,} rows...")
        pos_df = pos_df.sample(n=MAX_POSITIVE_ROWS, random_state=42)
    df = pd.concat([non_pos_df, pos_df]).sample(frac=1, random_state=42).reset_index(drop=True)

    print(f"Class distribution before split:")
    for label, name in LABEL_NAMES.items():
        cnt = (df["label"] == label).sum()
        print(f"  {name}: {cnt:,}")

    # 4. Split 80/10/10
    train_df, temp_df = train_test_split(
        df,
        test_size=0.20,
        stratify=df["label"],
        random_state=42,
    )
    val_df, test_df = train_test_split(
        temp_df,
        test_size=0.50,
        stratify=temp_df["label"],
        random_state=42,
    )

    print(f"\nRaw split sizes: train={len(train_df):,}, val={len(val_df):,}, test={len(test_df):,}")

    # 5. Undersample train to TRAIN_PER_CLASS per class
    train_balanced = undersample_to_target(train_df, TRAIN_PER_CLASS, np.random.default_rng(42))
    print(f"After undersampling: train={len(train_balanced):,}")
    print("Train label counts:", train_balanced["label"].value_counts().sort_index().to_dict())

    # 6. Check escalation condition
    min_class_count = train_balanced["label"].value_counts().min()
    if min_class_count < TRAIN_PER_CLASS:
        print(
            f"ESCALATION: Cannot reach {TRAIN_PER_CLASS}/class. "
            f"Min class has {min_class_count}. Proceeding with available data.",
            file=sys.stderr,
        )

    # 7. Write CSVs
    for name, split_df in [("train", train_balanced), ("val", val_df), ("test", test_df)]:
        out = PROCESSED_DIR / f"{name}.csv"
        split_df.to_csv(out, index=False, encoding="utf-8")
        print(f"Wrote {out} ({len(split_df):,} rows)")

    # 8. Write split_indices.json (review_id lists per split)
    indices = {
        "train": train_balanced["review_id"].tolist(),
        "val": val_df["review_id"].tolist(),
        "test": test_df["review_id"].tolist(),
    }
    idx_path = PROCESSED_DIR / "split_indices.json"
    with open(idx_path, "w", encoding="utf-8") as fh:
        json.dump(indices, fh, separators=(",", ":"))
    print(f"Wrote {idx_path} ({sum(len(v) for v in indices.values()):,} entries)")

    # 9. Write stats markdown
    write_stats(train_balanced, val_df, test_df)

    print("\nPreprocessing complete.")
    print(f"  train: {len(train_balanced):,}  val: {len(val_df):,}  test: {len(test_df):,}")


if __name__ == "__main__":
    main()
